// Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// User
export const SET_LIGHT_THEME = "SET_LIGHT_THEME";
export const SET_DARK_THEME = "SET_DARK_THEME";
export const SET_USER = "SET_USER";
export const SET_USER_CHANNELS = "SET_USER_CHANNELS";
export const SET_FOLLOWING_CHANNELS = "SET_FOLLOWING_CHANNELS";
// Loading bar
export const SET_LOADING_REF = "SET_LOADING_REF";

// currentVideo
export const SET_CURRENT_VIDEO = "SET_CURRENT_VIDEO";
export const SET_CURRENT_VIDEO_ERROR = "SET_CURRENT_VIDEO_ERROR";
export const INCR_VIDEO_COUNT = "INCR_VIDEO_COUNT";
export const SET_COMMENTS_SORT_TYPE = "SET_COMMENTS_SORT_TYPE";
export const UPDATE_VIDEO_LIKES = "UPDATE_VIDEO_LIKES";
export const UPDATE_VIDEO_DISLIKES = "UPDATE_VIDEO_DISLIKES";

// recmVideo
export const SET_RECM_VIDEO = "SET_RECM_VIDEO";
export const SET_RECM_VIDEO_ERROR = "SET_RECM_VIDEO_ERROR";

// likes
export const SET_USER_VID_LIKES = "SET_USER_VID_LIKES";
export const SET_USER_VID_DISLIKES = "SET_USER_VID_DISLIKES";

// channel
export const SET_VIDEO_CHANNEL = "SET_VIDEO_CHANNEL";
export const FOLL_UNFOLLOW_CHANNEL = "FOLL_UNFOLLOW_CHANNEL";
export const SET_CHANNEL_HOME_VIDEOS = "SET_CHANNEL_HOME_VIDEOS";
export const SET_FEATURED_CHANNELS = "SET_FEATURED_CHANNELS";
